// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBTM3P9qqO48DToiP40fWCO6k9xItjBIc',
    appId: '1:744037862434:web:c3d6cf6b8c325ef10f0e7b',
    messagingSenderId: '744037862434',
    projectId: 'skipsmaritiem-e4182',
    authDomain: 'skipsmaritiem-e4182.firebaseapp.com',
    storageBucket: 'skipsmaritiem-e4182.appspot.com',
    measurementId: 'G-LEW7GXTR3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgAOqV9T3IWd6-UTvunRLISng4paFN7IQ',
    appId: '1:744037862434:android:6b61ca7c76de97d20f0e7b',
    messagingSenderId: '744037862434',
    projectId: 'skipsmaritiem-e4182',
    storageBucket: 'skipsmaritiem-e4182.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzHEJBm3inG8RkWTXu3nFv86oxhWPyNJI',
    appId: '1:744037862434:ios:fd18795db7d51a840f0e7b',
    messagingSenderId: '744037862434',
    projectId: 'skipsmaritiem-e4182',
    storageBucket: 'skipsmaritiem-e4182.appspot.com',
    iosClientId: '744037862434-6v00u30ge6tns9clgs8figmrstcgfjrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.skipsmaritiem',
  );
}
